### ISSUE TITLE
체크마크 디자인 개선

### ISSUE THREAD

**Issue by mcnorton** [mcnorton/mome#10]
폰트를 ion-icon 으로 디자인 개선.

**Comment by mcnorton** [comment]
button 속 텍스트가 오버래핑 되도록 해야 함.
```css
parent {
    position: relative;
}
parent child {
    position: absolute;
    transform: translate(-40%, -50%);
}
```
